version: "3"

services:
  app:
    container_name: deep-space-store
    build: .
    ports:
      - "8080:8080" # Porta da aplicação Vue.js
      - "3001:3001" # Porta do JSON Server
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
